### ISSUE TITLE
Tab appears but no webcam, same as original version under OctoPrint 1.5

### ISSUE THREAD

**Issue by gruvin** [gruvin/OctoPrint-WebcamTab#1]
`imported from https://github.com/malnvenshorn/OctoPrint-WebcamTab/issues/14`

@DodgeDeBoulet wrote
> Is the [[link you've provided](https://github.com/gruvin/OctoPrint-WebcamTab/archive/master.zip)] a version that is supposed to work? Because it doesn't ... I get the exact same results as I reported in Tab created but no webcam display in 1.5.0rc3 #13.
> 
> [This version does work, however](https://github.com/jneilliii/OctoPrint-WebcamTab/archive/master.zip), provided in the linked issue by @jneilliii.

@DodgeDeBoulet Thanks for the feedback. Yes, it should. Did you remove the old/original plugin?

We should move this discussion to `https://github.com/gruvin/OctoPrint-WebcamTab/issues/1`

Meanwhile, I installed mine directly from the repo. I'll download that auto-generated master.zip and try it out. Strange.

**Comment by gruvin** [comment]
I'm in communication with @jneilliii over at https://github.com/OctoPrint/plugins.octoprint.org about taking over maintenance. First time doing that so just working through the official channels. My version is _supposed_ to work with all current major versions of Octoprint. Rest assured, it will.

**Comment by jneilliii** [comment]
So from further discussion with foosel and the linked issue above you may still have to make the changes that I did in my fork to get this to work in newer octoprint instances. Has something to do with the webcam container not existing during startup. I've had a discussion about it elsewhere, just can't remember where right now.

**Comment by gruvin** [comment]
> you may still have to make the changes that I did in my fork to get this to work in newer octoprint instances

I haven't looked at that version yet but I discovered this myself and addressed it by using the `onBoundAll` hook instead of `onAfterBound` (sp? x2)

**Comment by jneilliii** [comment]
that makes sense too, I bet it's not uninstalling the previous one since your pluginid is different it wouldn't "upgrade" the other one.

**Comment by jneilliii** [comment]
Basically if you just revert the plugin_identifier change and bump the version you should be good to for allowing installing over the other one.

**Comment by gruvin** [comment]
> ... since your pluginid is different it wouldn't "upgrade" the other one.

SInce I'm probably going to end up taking over maintenance (unless you wanted to, btw?) I'll change that back to match, right now.

**Comment by jneilliii** [comment]
no be my guest, I have too many already. I was just trying to help out.

**Comment by DodgeDeBoulet** [comment]
I had uninstalled jneilliii's version, including a cleanup of data, before
installing gruvin's version.

Didn't cleanup when I reverted back, although it worked fine.

**Comment by jneilliii** [comment]
So what I was seeing was what we think was related to access permissions, since when the initial page loads it isn't authenticated and therefore the objects don't exist for the plugin to grab them with jQuery and move them. In that scenario the call for grabbing the container would return a length of 0. I realized by moving the jquery moving part to where I did it bypassed the situation.

**Comment by jbuszkie** [comment]
Just to let you know, After I uninstalled the old plugin and then installed your fork from the URL, the tab now works again.  Thanks for picking this up!  I was going to have to figure out how to down grade if this didn't work!  I use the webcam tab all the time!!!

**Comment by IanEdwardJames** [comment]
Thank you, finally got this to work.  uninstalled the new one then installed the old one, then updated the old one then still wasn't working so uninstalled and installed the new one and still wasn't working so uninstalled again and cleaned up data then installed new one again.  Seems to be working now, I think the clean up data might be part of the key?

**Comment by gruvin** [comment]
@IanEdwardJames Hmmm. The plugin doesn't store any data, far as I know. Glad it worked though! ;-)

**Comment by gruvin** [comment]
My new version is now part of the official plugin repo. That is, when you install webcamtab from the official plugin library, you now get this new version, supporting Octoprint 1.3.6+, 1.4 and 1.5.

Closing issue now. Done and dusted. ;-)
