### ISSUE TITLE
Error with OctoPrint 1.7.0rc3 - tab created, but camera view not moved

### ISSUE THREAD

**Issue by pandel** [gruvin/OctoPrint-WebcamTab#12]
Hi!

With the latest OctoPrint 1.7.0rc3 release, the plugin does not work anymore. The Webcam tab is created, but the actual camera view is not moved to the new tab.

Regards,
Holger

**Comment by elfco** [comment]
i have write a quick fix for 1.7, a bit silly but it works ok xD

**Comment by pandel** [comment]
@hohenfelsjoe Thanks! Works for me, too!

**Comment by Dephrilibrium** [comment]
Yeah, can also confirm that elfcos webcam.js works (using hohenfelsjoes guide)
Much thanks @both

**Comment by conqueror433** [comment]
> Worked for me. Here is what I did:
> 
> mv /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/static/js/webcamtab.js /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/static/js/webcamtab.js.orig
> 
> curl https://raw.githubusercontent.com/elfco/OctoPrint-WebcamTab/patch-1/octoprint_webcamtab/static/js/webcamtab.js > /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/static/js/webcamtab.js
> 
> chown pi.pi /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/static/js/webcamtab.js
> 
> chmod 644 /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/static/js/webcamtab.js

Sorry I am not very familier with the coding. Are above lines need to be pasted on by one in RPi SSH Putty?
Or I have to manually move something?

**Comment by harryfiedify** [comment]
@conqueror433 yes, log in to the RPi using SSH (or local terminal) and paste each line separately, that's all

This will replace the webcamtab.js from the plugin with a patched file for the new OctoPrint version. (and set some necessary file permissions.)
If you mess anything up, the old file is renamed to webcamtab.js.orig

**Comment by conqueror433** [comment]
@harryfiedify Thanks a Ton..!! It Worked..
