### ISSUE TITLE
1.9.0 breaks things

### ISSUE THREAD

**Issue by jneilliii** [gruvin/OctoPrint-WebcamTab#16]
With OctoPrint 1.9.0 several things have been redone relative to the webcam and it seems with this plugin there are js errors on page load. Maybe the same changes mentioned by maInvenshorn in #14 might help the situation. I'd recommend switching OctoPrint's release channel in Software Update settings to maintenance rcs and give a test. Seems to be an issue with the onAllBound callback. 

[webcamtab js console errors.log](https://github.com/gruvin/OctoPrint-WebcamTab/files/11346205/webcamtab.js.console.errors.log)

**Comment by Letme** [comment]
This is now the issue as 1.9.0 is officially out of RC phase.

**Comment by alex1platon** [comment]
i pushed a fix for this issue it just needs to be approved and released (I'm a sub-beginner-noob in github matters so hopefully did that right)

**Comment by jneilliii** [comment]
You're right, it does appear that it is an OctoPrint 1.9.0 issue maybe. I installed the original un-patched version in 1.8.7 and it works fine. Adjusting my patch now to handle that properly.

**Comment by jneilliii** [comment]
Your patch works perfectly in 1.9.0 and your PR looks perfectly fine. Just got to get @gruvin to merge it now and bump the version and release.

**Comment by alex1platon** [comment]
@gruvin i'm a complete idiot when it comes to github.  is the release generated automatically or do i need to do anything about it?  pardon my ignorance :|

**Comment by jneilliii** [comment]
technically, you need to update the plugin_version in setup.py and then on GitHub someone with the rights create the release.

**Comment by gruvin** [comment]
oh. Sorry guys. Was in a hurry. I'll sort that now.

**Comment by gruvin** [comment]
I'll find a place to install OP 1.9 and test this properly now, after the fact and all.
@jneilliii if you'd like to take back the plugin maintenance then by all means. I only stepped in when you appeared to be unavailable for an extended time, around covid 'n'all if you know what I mean. (Also, I get so many otherwise meaningless Github emails that I keep missing these ones that I care about. :/)

**Comment by jneilliii** [comment]
This wasn't my plugin, so by all means you keep it.

**Comment by gruvin** [comment]
> This wasn't my plugin, so by all means you keep it.
Oh! My bad. Dang. Can't say I didn't try. :P

**Comment by gruvin** [comment]
@alex1platon should be good to go now. I'm still upgrading one of my printers to 1.9.0 but have confirmed that your changes didn't break v1.8.6.

Thanks for the help! :-)

**Comment by gruvin** [comment]
Confirmed working without issue on my system with all my other plugins. Yay!
