### ISSUE TITLE
the stream is removed from the control tab but no webcam tab 

### ISSUE THREAD

**Issue by jjl40** [gruvin/OctoPrint-WebcamTab#3]
[webcam_tab.txt](https://github.com/gruvin/OctoPrint-WebcamTab/files/5683865/webcam_tab.txt)

OctoPrint v 1.4.2 
Pi 4 4G
Made several attempts to load this through the plugin manager and from the GitJub zip file, No luck.

**Comment by gruvin** [comment]
Fixed now though, right? Sorry, issue notifications got lost in spam.

**Comment by gruvin** [comment]
Please re-open the issue (by adding a new comment) if a problem remains. Thanks.
