### ISSUE TITLE
1.6 compatibility

### ISSUE THREAD

**Issue by nurglexp** [gruvin/OctoPrint-WebcamTab#7]
Could you update for compatibility with 1.6
I just get a blank screen since updating.

**Comment by tfurci** [comment]
I added this this text to js file to fix it. You can download zip file and install it youself or wait for owner to fix.
[OctoPrint-WebcamTab-0.2.0_1.6.0fix.zip](https://github.com/gruvin/OctoPrint-WebcamTab/files/6399959/OctoPrint-WebcamTab-0.2.0_1.6.0fix.zip)

case "1.6":
                _enableWebcamOvveride = self.methodOverrides['_enableWebcam_v1_5']
                onTabChangeOverride = self.methodOverrides['onTabChange_common']
                webcamElements = $("#control > #webcam_container, #control > #webcam_hls_container, #control > div:nth-child(3)")
                hintDivEl = webcamElements[2]
                break

**Comment by ElNinjaGaiden** [comment]
I sent a PR to fix this matter: https://github.com/gruvin/OctoPrint-WebcamTab/pull/8

**Comment by dimo414** [comment]
It would be great if the error message was also displayed in the Webcam tab, rather than only [in the console](https://github.com/gruvin/OctoPrint-WebcamTab/blob/f8dbc93/octoprint_webcamtab/static/js/webcamtab.js#L148). Even if it might not work for all future releases it'd be helpful in cases (like this one) where the tab displays but doesn't pull in any content.

I also see a separate message in the console that might be related to 1.6:

    Did not bind view model WebcamTabViewModel to target #webcamtab since it does not exist

**Comment by ldiegos** [comment]
It seems not no work version WebcamTab: 0.2.0  with octoprint OctoPrint: 1.6.0
The tab appear, but is empty, also the webcam remain in the Control tab.

**Comment by tfurci** [comment]
I made fork to fix this you can install it with url in plugin manager.
https://github.com/tfurci/OctoPrint-WebcamTab/releases/tag/0.2.1

**Comment by ElNinjaGaiden** [comment]
> It seems not to work version WebcamTab: 0.2.0 with octoprint OctoPrint: 1.6.0
> The tab appear, but is empty, also the webcam remain in the Control tab.

I have installed my branch on my 3 printers using OctoPrint 1.6.0 and it works as expected

**Comment by ElNinjaGaiden** [comment]
It kind ofIt kind feels like this repository is not maintained anymore

**Comment by ldiegos** [comment]
I use your zip @ElNinjaGaiden and works perfectly... maybe you can try to get the ownership of this plugging and continue maintaining it.

**Comment by gruvin** [comment]
This repo is maintained. These issues got lost in spam. Apologies.
The recent update looping is now fixed. Should be fixed now => 0.2.11 released.
