### ISSUE TITLE
Problem to update to 0.2.1

### ISSUE THREAD

**Issue by DariBer** [gruvin/OctoPrint-WebcamTab#9]
I try to update my 0.2.0 to latest 0.2.1. I see a popup in OctoPrint to upgrade, I press to upgrade and it ends with "The update finished successfully and the server will now be restarted."

After the reboot I still get a popup to upgrade from 0.2.0 to 0.2.1. When I check what version I have installed, it say 0.2.0.

I have tried to uninstall (and clean up) But I still only get 0.2.0.

What could be the problem?

**Comment by gruvin** [comment]
My bad. should be fixed now => 0.2.11 released.
